magazine-service:
  service-name: magazine-service
  base-path: /api/v1
  scheduler:
    cron: 0 0 3 * * *

server:
  tomcat:
    threads:
      max: 200

preliquibase:
  sql-script-references: "classpath:database/preliquibase/schema.sql"

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: ${magazine-service.service-name}
  cloud:
    config:
      enabled: false
  jpa:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    default_schema: magazine_service_scheme
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        default_schema: ${spring.jpa.default_schema}
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 7000
    driver-class-name:
  liquibase:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    default-schema: ${spring.jpa.default_schema}
    change-log: "classpath:database/changelog/changelog.xml"
    drop-first: true
    driver-class-name: ${spring.datasource.driver-class-name}
  kafka:
    admin:
      enabled: true
      bootstrap-servers: localhost:9092
      topic:
        enabled: true
        partitions: 1
        replicas: 1
        retention-ms: 86000
        topic-name: product_topic_sending_rs
    producer:
      enabled: true
      bootstrap-servers: localhost:9092
    consumer:
      enabled: true
      bootstrap-servers: localhost:9092
      topic-name: product_topic_sending_rq
      max-poll-records: 500
    security:
      protocol: PLAINTEXT

  data:
    redis:
      host: localhost
      port: 6379
      password: admin
      enabled: true

management:
  info:
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - prometheus
          - httptrace
          - cache
          - caches
          - loggers
          - metrics
          - sessions
          - threaddump
          - heapdump
          - configprops